application:
  name: pie-backend
  project: pie-backend
  organization: QoveryCommunity
databases:
- type: postgresql
  version: "12"
  name: my-postgresql
routers:
- name: main
  routes:
  - application_name: pie-backend
    paths:
    - /
